id: PD4DBB8BD
initial_creation_type: input
source_metadata:
  title: Lama Rigdzin Nyima Series
  language: zh
  description: Texts by Lama Rigdzin Nyima (rig 'dzin nyi ma, b. 1931), a tertön from
    Golok.
  volume:
    f63c818d6edb42c59dcb2bd0c58230c6:
      title: The Final Testament of Yukhok Chatralwa as Transmitted to Lama Rigdzin
        Nyima
      parent: Testament
created_at: '2022-03-01T00:33:40.753698'
last_modified_at: '2022-03-01T00:33:40.753702'
